# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: rsync-plugin-fuel8
  type: group
  requires: [deploy_start]
  required_for: [deploy_end]
  tasks: [hiera, globals, tools, logging, firewall, rsync-plugin-fuel8-deployment-puppet]
  role: [rsync-plugin-fuel8]
  parameters:
          strategy:
                  type: parallel

- id: rsync-plugin-fuel8-deployment-puppet
  type: puppet
  groups: [rsync-plugin-fuel8]
  requires: [deploy_start]
  required_for: [deploy_end]
  parameters: 
    puppet_manifest: "puppet/manifests/rsyncback.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: rsync-plugin-cron
  role: [compute,base-os]
  type: puppet
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
          puppet_manifest: "puppet/manifests/cron.pp"
          puppet_modules: "puppet/modules:/etc/puppet/modules"
          timeout: 3600

- id: rsync-plugin-fuel8-pre-deployment-sh
  version: 2.0.0
  type: shell
  role: [rsync-plugin-fuel8]
  required_for: [deploy_start]
  parameters:
    cmd: "mkdir -p /var/tmp/rsync_backup && chmod 0777 /var/tmp/rsync_backup"
    cwd: "/"
    retries: 3
    interval: 20
    timeout: 180

- id: rsync-plugin-fuel8-firstbackup
  version: 2.0.0
  type: puppet
  role: [compute, base-os]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
          cmd: ""
          puppet_manifest: "puppet/manifests/firstbackup.pp"
          puppet_modules: "puppet/modules:/etc/puppet/modules"
          timeout: 3600
